---
- hosts: all
  become: yes

  pre_tasks:
    - name: update apt caches
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: upgrade all packages
      apt:
        name: "*"
        state: latest

  roles:
    - storage
    - geerlingguy.nfs

  tasks:
    - name: install base packages
      apt:
        pkg:
          - curl
          - gawk
          - grep
          - jq
          - unzip
          - util-linux
          - attr
          - tree
        state: present

    - name: remove snapd
      apt:
        pkg: snapd
        state: absent
        purge: yes

    - name: install iscsi
      apt:
        pkg:
          # needed for iSCSI drivers
          - linux-modules-extra-raspi
          - open-iscsi
        state: present

    - name: enable iscsi daemon
      service:
        name: iscsid
        enabled: yes
        state: started

    - name: install build tooling
      apt:
        pkg:
          - build-essential
          - git
          - golang
        state: present
